# This rule is not used by the project markdown-view itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over view.yktakaha4.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: markdown-view
    app.kubernetes.io/managed-by: kustomize
  name: markdownview-admin-role
rules:
- apiGroups:
  - view.yktakaha4.github.io
  resources:
  - markdownviews
  verbs:
  - '*'
- apiGroups:
  - view.yktakaha4.github.io
  resources:
  - markdownviews/status
  verbs:
  - get
